### ISSUE TITLE
Keep track of bans/quiets

### ISSUE THREAD

**Issue by emersonveenstra** [hashweb/ella#15]
I thinnk it would be helpful to have ella see when there's a ban, and follow up with the op either in pm or #web-social for a reason and ban time. After the specified time, ella will ping the op to remove the ban. (I think we had a discussion about having the bot remove bans automatically, and we decided it wasn't a good idea, but that would also be an option if people are open to it)

**Comment by Jayflux** [comment]
I can create a bans table in the hashweb database, then have the bot POST to hashweb when someone is banned to update it.
We can then view bans and times in the browser (and cross reference them with the logs we already have)
We can also have the bot POST notes alongside each ban so we know why they're banned etc

**Comment by Jayflux** [comment]
Marking this as done
http://hashweb.org/stats/bans/
